version: '2.4'

services:
        web:
                init: true
                build: 
                        context: .
                        target: prod
                ports: 
                        - "3000:3000"
                volumes:
                        - .:/node/app:delegated
                        - /node/app/node_modules
